services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=opal-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword

volumes:
  postgres_data:
# docker compose up -> to run the file
# docker compose up --build -> to build
# docker compose watch -> to watch for changes
